[build]
target = "xtensa-esp32s3-espidf"

[target.xtensa-esp32s3-espidf]
linker = "ldproxy"
runner = "sudo espflash flash --monitor"
# Extending time_t for ESP IDF 5: https://github.com/esp-rs/rust/issues/110
rustflags = [ "--cfg",  "espidf_time64"] 

[unstable]
build-std = ["std", "panic_abort"]

[env]
MCU="esp32s3"
ESP_LOGLEVEL="INFO"
# Note: this variable is not used by the pio builder (`cargo build --features pio`)
ESP_IDF_VERSION = "v5.2.2"
# Workaround for https://github.com/esp-rs/esp-idf-template/issues/174 
CRATE_CC_NO_DEFAULTS = "1"
