import { Button, VerticalBox } from "std-widgets.slint";

export component AppWindow inherits Window {
    preferred-width: 240px;
    preferred-height: 240px;
    VerticalLayout {
        alignment: center;
        HorizontalLayout {
            alignment: center;
            Text {
                horizontal-alignment: center;
                text: "Hello, world!";
            }
        }

        HorizontalLayout {
            alignment: center;
            Button {
                text: "Click Me";
                clicked => {
                    // Handle button click
                }
            }
        }
    }
}
